version: '3.7'

services:
  devopstest:
    image: devopstest
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
